{% set name = "mne-qt-browser" %}
{% set version = "0.4.0" %}
{% set sha256 = 8aa7cb6487e88136700a20d95a00adaba7f0c5d0457d739d53dab326544d1032" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - mne-base >=0.24
    - numpy
    - pyqtgraph >=0.12.3
    - python
    - qtpy
    - scipy
    - colorspacious
    - darkdetect
    - qdarkstyle
    - pyopengl  # [osx]
    - scooby

test:
  imports:
    - mne_qt_browser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mne-tools/mne-qt-browser
  summary: A new backend based on pyqtgraph for the 2D-Data-Browser in MNE-Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
    - marsipu
