{% set name = "mne-qt-browser" %}
{% set version = "0.2.1" %}
{% set sha256 = "5fb5334cf0c2b8976d66700239515c95c74bcbc191a427d3176f2c63eb140316" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base
    - mne-base >=0.24
    - numpy
    - pyqt >=5.12
    - pyqtgraph >=0.12.3
    - python >=3.7
    - qtpy
    - scipy

test:
  imports:
    - mne_qt_browser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mne-tools/mne-qt-browser
  summary: A new backend based on pyqtgraph for the 2D-Data-Browser in MNE-Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
    - marsipu
