{% set name = "mne-qt-browser" %}
{% set version = "0.7.0" %}
{% set sha256 = "d378f38af2639aaaa1b191569dbeca82849a94f4cce427b96ded30e4be33602c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - qtpy
    - scooby
    - mne-base >=1.0
    - pyqtgraph >=0.12.3
    - pyopengl
    - darkdetect
    - qdarkstyle

test:
  imports:
    - mne_qt_browser
  commands:
    - pip check
    - python -c "import mne_qt_browser; ver = mne_qt_browser.__version__; assert ver == '{{ version }}', ver"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mne-tools/mne-qt-browser
  summary: A new backend based on pyqtgraph for the 2D-Data-Browser in MNE-Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
    - marsipu
