{% set name = "mne-qt-browser" %}
{% set version = "0.2.6" %}
{% set sha256 = "199b7386f3d3649df9aacd0092912c65cb9403d6f70375586953742e39ed84fc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - mne-base >=0.24
    - numpy
    - pyqt >=5.12
    - pyqtgraph >=0.12.3
    - python
    - qtpy
    - scipy
    - colorspacious
    - pyopengl  # [osx]
    - scooby

test:
  imports:
    - mne_qt_browser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mne-tools/mne-qt-browser
  summary: A new backend based on pyqtgraph for the 2D-Data-Browser in MNE-Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
    - marsipu
