{% set name = "mne-qt-browser" %}
{% set version = "0.6.2" %}
{% set sha256 = "4dc265e3eb5d8577c4da11e8a2bf5aeb7c7e2f73fa54d594a8b2d0e0b04ae5d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python >=3.8
    - setuptools >=45
    - setuptools_scm >=6.2
    - git
  run:
    - python >=3.8
    - packaging
    - setuptools >=65
    - numpy
    - scipy
    - matplotlib-base
    - qtpy
    - scooby
    - mne-base >=1.0
    - pyqtgraph >=0.12.3
    - colorspacious
    - pyopengl
    - darkdetect
    - qdarkstyle

test:
  imports:
    - mne_qt_browser
  commands:
    - pip check
    - python -c "import mne_qt_browser; ver = mne_qt_browser.__version__; assert ver == '{{ version }}', ver"
  requires:
    - pip

about:
  home: https://github.com/mne-tools/mne-qt-browser
  summary: A new backend based on pyqtgraph for the 2D-Data-Browser in MNE-Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
    - marsipu
